#!/bin/sh

. ~/.local/bin/statusbar/sb-utils

for bat in /sys/class/power_supply/BAT?*; do
  capacity="$(cat "$bat"/capacity 2>&1)"
  if [ "$capacity" -gt 95 ]; then
    status="󰁹"
  elif [ "$capacity" -gt 90 ]; then
    status="󰂂"
  elif [ "$capacity" -gt 80 ]; then
    status="󰂁"
  elif [ "$capacity" -gt 70 ]; then
    status="󰂀"
  elif [ "$capacity" -gt 60 ]; then
    status="󰁿"
  elif [ "$capacity" -gt 50 ]; then
    status="󰁾"
  elif [ "$capacity" -gt 40 ]; then
    status="󰁽"
  elif [ "$capacity" -gt 30 ]; then
    status="󰁼"
  elif [ "$capacity" -gt 20 ]; then
    status="󰁻"
  elif [ "$capacity" -gt 10 ]; then
    status="󰁺"
  else
    status="󰂃"
  fi
  status="$status$capacity%"

  bat_status="$(cat "$bat"/status 2>&1)"
  case "$bat_status" in
    Full) status=$(sb-fg 󱐋 $COL_ANSI_4) ;;
    Discharging)
      if [ "$capacity" -gt 70 ]; then
        status=$(sb-fg "$status" $COL_ANSI_2)
      elif [ "$capacity" -gt 20 ]; then
        status=$(sb-fg "$status" $COL_ANSI_3)
      else
        status=$(sb-fg "$status" $COL_ANSI_1)
      fi
      ;;
    Charging) status=$(sb-fg "$status" $COL_ANSI_2) ;;
    "Not charging") status=$(sb-fg " $status" $COL_ANSI_5) ;;
    Unknown|*) status="?$status" ;;
  esac

  printf "%s" "$status"
done

