#!/bin/sh

# ANSI 4-bit color codes
export COL_ANSI_0=#000000  # black
export COL_ANSI_1=#FF0000  # red
export COL_ANSI_2=#00FF00  # green
export COL_ANSI_3=#FFFF00  # yellow
export COL_ANSI_4=#0000FF  # blue
export COL_ANSI_5=#FF00FF  # magenta
export COL_ANSI_6=#00FFFF  # cyan
export COL_ANSI_7=#FFFFFF  # white

# dwm status2d color formatting
sb-fg() {
  text=$1; color=$2
  if [ -n "$color" ]; then printf "^c%s^%s^d^" "$color" "$text"
  else printf "%s" "$text"
  fi
}

