#!/bin/sh

set -e

. ~/.local/bin/statusbar/sb-utils

is-muted() {
  wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>&1 | grep -q "MUTED"
}

get-volume() {
  wpctl_output=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null) || return 1
  frac=$(printf '%s\n' "$wpctl_output" | tail -n 1 | cut -d' ' -f2)
  echo "$frac * 100 / 1" | bc
}

if is-muted; then
  status=$(sb-fg " " "$COL_ANSI_1")
elif volume=$(get-volume); then
  if [ "$volume" -ge 70 ]; then
    status=" $volume%"
  elif [ "$volume" -ge 30 ]; then
    status=" $volume%"
  else
    status=" $volume%"
  fi
else
  status=$(sb-fg " ?" "$COL_ANSI_5")
fi

printf "%s" "$status"

