#!/bin/sh

set -e

DOTBOT_DIR=".dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "$0")" && pwd -P)"
# fully qualified
DOTBOT_FQ_BIN="${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}"

cd "${BASEDIR}"

git submodule update --init --recursive --depth 1

MODULE_CONFIGS="
    x/x.conf.yaml
    picom/picom.conf.yaml
    fontconfig/fontconfig.conf.yaml
    sxhkd/sxhkd.conf.yaml
    script/script.conf.yaml
    themes/themes.conf.yaml
    gtk3/gtk3.conf.yaml
"

MODULE_ROOT_CONFIGS="
    x/x.root.conf.yaml
"

sh ./.install-modules "$DOTBOT_FQ_BIN" "$BASEDIR" "$MODULE_CONFIGS"
# sudo sh ./.install-modules "$DOTBOT_FQ_BIN" "$BASEDIR" "$MODULE_ROOT_CONFIGS"

