#!/bin/sh

set -e

CONFIG="install.conf.yaml"
BASEDIR="$(cd "$(dirname "$0")" && pwd -P)"
DOTBOT_DIR=".dotbot"
DOTBOT_BIN="bin/dotbot"
MODULE_CONFIG="
  x
  picom
  fontconfig
  sxhkd
  script
  themes
  gtk3
  mpv
"

is_root_config() {
  for arg in "$@"; do
    if [ "$arg" = "--root" ]; then
      printf 1; return 0
    fi
  done
}

install_modules() {
  dotbot_bin=$1; base_dir=$2; modules=$3; shift 3
  is_root=$(is_root_config "$@")
  for cfg in $modules; do
    config_dir="$base_dir/$cfg"
    config="$config_dir/$cfg".conf.yaml
    if [ -f "$config" ]; then
      $dotbot_bin -d $config_dir -c $config
    fi
    [ "$is_root" = "1" ] && root_config="$config_dir/$cfg".root.conf.yaml
    if [ -f "$root_config" ]; then
      $dotbot_bin -d $config_dir -c $root_config
    fi
  done
}


cd "${BASEDIR}"
git submodule update --init --recursive
install_modules "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" "$BASEDIR" "$MODULE_CONFIG" "$@"
