#!/bin/sh

PROMPT="󰌾🔖 gopass totp:"

set-gtk-pinentry() {
  printf '%s\n' gtk > "$XDG_RUNTIME_DIR/pinentry-mode"
}

# relies on https://github.com/sanvew/dotfiles/blob/main/gnupg/arch/pinentry
entry="$(gopass ls --flat | dmenu -i -p "$PROMPT" -l 0)"
if [ -n "$entry" ]; then
  set-gtk-pinentry
  gopass totp -c "$entry"
  # TODO: 20260922-000151: send notifcation if entry doesnt have totp
fi
