#!/bin/sh

PROMPT="⚡ Power:"
SCREENLOCK_SCRIPT="screenlock"

LABEL_REBOOT="🔄 Reboot"
LABEL_POWEROFF="⏻ Power Off"
LABEL_HIBERNATE="🛌 Hibernate"
LABEL_LOCK="🔒 Lock"

_reboot() {
  loginctl reboot
}

_poweroff() {
  loginctl poweroff
}

_hibernate() {
  [ -x "$(command -v $SCREENLOCK_SCRIPT)" ] && $SCREENLOCK_SCRIPT -i
}

_screenlock() {
  [ -x "$(command -v $SCREENLOCK_SCRIPT)" ] && $SCREENLOCK_SCRIPT
}

show-menu() {
  printf '%s\n' \
    "$LABEL_HIBERNATE" \
    "$LABEL_LOCK" \
    "$LABEL_REBOOT" \
    "$LABEL_POWEROFF"
}

selection=$(show-menu | dmenu -i -p "$PROMPT")

case $selection in
  "$LABEL_REBOOT" | "reboot") _reboot ;;
  "$LABEL_POWEROFF" | "poweroff") _poweroff ;;
  "$LABEL_HIBERNATE" | "hibernate") _hibernate ;;
  "$LABEL_LOCK" | "screenlock") _screenlock ;;
  *) exit 0 ;;
esac
