#!/bin/sh

PROMPT="power"
SCREENLOCK_SCRIPT="screenlock"

reboot_() {
  loginctl reboot
}

poweroff_() {
  loginctl poweroff
}

hibernate_() {
  [ -x "$(command -v $SCREENLOCK_SCRIPT)" ] && $SCREENLOCK_SCRIPT -i
}

screenlock_() {
  [ -x "$(command -v $SCREENLOCK_SCRIPT)" ] && $SCREENLOCK_SCRIPT
}

show-menu() {
  printf '%s\n' \
    "hibernate" \
    "screenlock" \
    "reboot" \
    "poweroff"
}

selection=$(show-menu | dmenu -i -p "$PROMPT")

case $selection in
  "reboot") reboot_ ;;
  "poweroff") poweroff_ ;;
  "hibernate") hibernate_ ;;
  "screenlock") screenlock_ ;;
  *) exit 0 ;;
esac
