#!/bin/sh

set -e

primary() {
    echo -n "$1" | awk '$2=="connected" && $3=="primary" {print $1, $4}' | cut -d '+' -f1
}

secondary() {
    echo -n "$1" | awk '$2=="connected" && $3!="primary" {print $1, $3}' | cut -d '+' -f1
}

get-output() {
    echo -n "$1" | awk '{print $1}'
}

get-w() {
    echo -n "$1" | awk '{print $2}' | cut -d 'x' -f1
}

get-h() {
    echo -n "$1" | awk '{print $2}' | cut -d 'x' -f2
}

bc-abs() {
    echo "val=$1; if(val < 0) -val else val" | bc
}

align-center() {
    bc-abs $(echo "($1-$2)/2" | bc)
}

run-xrandr() {
    primary_out=$1; primary_x=$2; primary_y=$3
    secondary_out=$4; secondary_x=$5; secondary_y=$6

    xrandr \
        --output "$primary_out" --auto --pos "$primary_x"x"$primary_y" \
        --output "$secondary_out" --auto --pos "$secondary_x"x"$secondary_y"
}

arrange() {
    extend_direction=$1

    xrandr_output=$(xrandr)
    connected_screens=$(echo "$xrandr_output" | grep ' connected')

    primary_screen=$(primary "$connected_screens")
    p_o=$(get-output "$primary_screen")
    p_w=$(get-w "$primary_screen")
    p_h=$(get-h "$primary_screen")

    secondary_screen=$(secondary "$connected_screens")
    s_o=$(get-output "$secondary_screen")
    s_w=$(get-w "$secondary_screen")
    s_h=$(get-h "$secondary_screen")

    case "$extend_direction" in
        top|t)
            aligned_width=$(align-center $p_w $s_w)
            run-xrandr $p_o $aligned_width $s_h $s_o 0 0
            ;;
        bot|bottom|b)
            aligned_width=$(align-center $p_w $s_w)
            run-xrandr $p_o $aligned_width 0 $s_o 0 $p_h
            ;;
        right|r)
            run-xrandr $p_o 0 0 $s_o $p_w 0
            ;;
        left|l)
            run-xrandr $p_o $s_w 0 $s_o 0 0
            ;;
        *)
            echo "unknown direction"
            exit 1
            ;;
    esac
}

######## main ########
if [ -z "$1" ]; then
    echo "direction not provided"
    exit 1
fi
arrange $1


