#!/bin/sh

HIBERNATE_TIMEOUT="$(echo "20*60" | bc)"
IMMEDIATE_TIMEOUT=2
KB_LAYOUT_CTL_CMD="$HOME/.local/bin/kb-layout-ctl"
HIBERNATE_CMD="loginctl hibernate"
SUSPEND_CMD="loginctl hybrid-sleep"
SCREENLOCK_CMD=slock
IMMEDIATE_MODE=0
SUSPEND_MODE=0
XIDLEHOOK_PID=

start_idlehook() {
    [ -x "$(command -v xidlehook)" ] || return 0
    [ "$SUSPEND_MODE" -eq 1 ] && SLEEP_CMD="$SUSPEND_CMD" || SLEEP_CMD="$HIBERNATE_CMD"
    xidlehook --detect-sleep --timer "$HIBERNATE_TIMEOUT" "$SLEEP_CMD" "" &
    XIDLEHOOK_PID=$!
    [ "$IMMEDIATE_MODE" -eq 1 ] && (sleep "$IMMEDIATE_TIMEOUT" && $SLEEP_CMD) &  # give some time to actually lock
}

stop_idlehook() {
    [ -n "$XIDLEHOOK_PID" ] || return 0
    kill "$XIDLEHOOK_PID" 2>/dev/null
}

store_kb_layout() {
  [ -x "$(command -v xkblayout-state)" ] || return 1
  xkblayout-state print "%s"
  $KB_LAYOUT_CTL_CMD us 2>/dev/null
}

restore_kb_layout() {
  layout=$1; shift
  [ -n "$layout" ] && $KB_LAYOUT_CTL_CMD "$layout"
}

while [ $# -gt 0 ]; do
    case $1 in
        -i|--immediate) IMMEDIATE_MODE=1 ;;
        # TODO: 20260907-193731 cant figure out how to turn off fan immediately on suspend
        -s|--suspend) SUSPEND_MODE=1 ;;
    esac
    shift
done

if [ -x "$(command -v $SCREENLOCK_CMD)" ]; then
  start_idlehook
  prev_layout="$(store_kb_layout)"
  $SCREENLOCK_CMD
  restore_kb_layout "$prev_layout"
  stop_idlehook
fi
