#!/bin/sh

set -e

FFMPEG_EXEC="ffmpeg"
SLOP_EXEC="slop"
XDOTOOL_EXEC="xdotool"
XCLIP_EXEC="xclip"
DATE_FMT="%Y%m%d%H%M%S"
SCREENSHOT_PATH=~/Pictures/screenshot
SCREENSHOT_EXT="png"

usage() {
  cat <<EOF
Usage: screenshot [options]
Options:
-e    Capture the entire screen (default).
-m    TODO: Capture focused monitor.
-i    Interactively select target.
-w    Capture window.
-c    Copy the result to the clipboard.
-v    TODO: Screen-cast recording.
-h    Show this help message.
EOF
}

# parsed options
CAPTURE_MODE=""
INTERACTIVE_OPTION=0
CLIPBOARD_OPTION=0
parse-options() {
  while getopts ":eiwch" opt 2>/dev/null; do
    case "$opt" in
      e|w)
        if [ -n "$CAPTURE_MODE" ]; then
          echo "Multiple options selected: -$CAPTURE_MODE, -$opt"
          exit 1
        fi
        CAPTURE_MODE="$opt"
        ;;
      i) INTERACTIVE_OPTION=1 ;;
      c) CLIPBOARD_OPTION=1 ;;
      h) usage ;;
      \?) echo "illegal option: -$OPTARG" ; usage ; exit 1 ;;
      :) echo "option -$OPTARG requires an argument"; exit 1 ;;
    esac
  done
  if [ -z "$CAPTURE_MODE" ]; then
    CAPTURE_MODE="e"
  fi
}

executable-exist() {
  _exec=$1; msg=$2
  if [ ! -x "$(command -v "$_exec")" ]; then
    echo "$msg executable not found."
    exit 1
  fi
}

screenshot-dest() {
  if [ "$CLIPBOARD_OPTION" -eq 1 ]; then
    echo "-f image2pipe -"
  else
    mkdir -p "$SCREENSHOT_PATH"
    echo "$SCREENSHOT_PATH"/$(date +%Y%m%d%H%M%S)."$SCREENSHOT_EXT"
  fi
}

select-region() {
  executable-exist "$SLOP_EXEC" slop
  read x y w h <<< $("$SLOP_EXEC" -f '%x %y %w %h')
  echo "-s "${w}x${h}" -i "$DISPLAY+$x,$y""
}

select-window() {
  WIN_ID=
  if [ "$INTERACTIVE_OPTION" -eq 1 ]; then
    executable-exist "$SLOP_EXEC" slop
    read WIN_ID <<< $("$SLOP_EXEC" -f '%i')
  else
    executable-exist "$XDOTOOL_EXEC" xdotool
    WIN_ID=$("$XDOTOOL_EXEC" getactivewindow)
  fi
  echo "-window_id "$WIN_ID" -i "$DISPLAY""
}

screenshot() {
  executable-exist "$FFMPEG_EXEC" ffmpeg
  CMD=""$FFMPEG_EXEC" -hide_banner -loglevel error -f x11grab"
  case "$CAPTURE_MODE" in
    e) [ "$INTERACTIVE_OPTION" -eq 1 ] && CMD="$CMD $(select-region)" || CMD="$CMD -i $DISPLAY" ;;
    w) CMD="$CMD $(select-window)" ;;
    *)
      echo "Unknowm capture mode $CAPTURE_MODE"
      exit 1
      ;;
  esac
  CMD="$CMD -frames:v 1 -vcodec png $(screenshot-dest)"
  if [ "$CLIPBOARD_OPTION" -eq 1 ]; then
    executable-exist "$XCLIP_EXEC" xclip
    $CMD | "$XCLIP_EXEC" -selection clipboard -t image/$SCREENSHOT_EXT
  else
    $CMD
  fi
}


parse-options "$@"
screenshot

