#!/bin/sh

HIBERNATE_TIMEOUT="$(echo "20*60" | bc)"
IMMEDIATE_TIMEOUT=2
KB_LAYOUT_CTL_CMD="$HOME/.local/bin/kb-layout-ctl"
HIBERNATE_CMD="loginctl hibernate"
SUSPEND_CMD="loginctl suspend-then-hibernate"
SCREENLOCK_CMD=slock
IMMEDIATE_MODE=0
MODE=""
XIDLEHOOK_PID=

usage() {
  cat <<EOF
Usage: screenlock [options]
Options:
-s --suspend    Suspend system to memory (default).
-b --hibernate  Suspend system to disc.
-i --immediate  Suspen immediately.
-h --help       Show this help message.
EOF
}

start_idlehook() {
    if [ ! -x "$(command -v xidlehook)" ]; then
      echo "\"xidlehook\" executable not found."
      exit 1
    fi
    case "$MODE" in
      s) SLEEP_CMD="$SUSPEND_CMD" ;;
      h) SLEEP_CMD="$HIBERNATE_CMD" ;;
    esac
    xidlehook --detect-sleep --timer "$HIBERNATE_TIMEOUT" "$SLEEP_CMD" "" &
    XIDLEHOOK_PID=$!
    if [ "$IMMEDIATE_MODE" -eq 1 ]; then
      # give some time to actually lock
      sleep "$IMMEDIATE_TIMEOUT"
      $SLEEP_CMD &
    fi
}

stop_idlehook() {
    [ -n "$XIDLEHOOK_PID" ] || return 0
    kill "$XIDLEHOOK_PID" 2>/dev/null
}

store_kb_layout() {
  [ -x "$(command -v xkblayout-state)" ] || return 1
  xkblayout-state print "%s"
  $KB_LAYOUT_CTL_CMD us 2>/dev/null
}

restore_kb_layout() {
  layout=$1; shift
  [ -n "$layout" ] && $KB_LAYOUT_CTL_CMD "$layout"
}

while [ $# -gt 0 ]; do
    case $1 in
        -i|--immediate) IMMEDIATE_MODE=1 ;;
        -s|--suspend)
          if [ -n "$MODE" ]; then
            echo "Multiple options selected: -i, -s"
            exit 1
          fi
          MODE="s"
          ;;
        -b|--hibernate)
          if [ -n "$MODE" ]; then
            echo "Multiple options selected: -i, -s"
            exit 1
          fi
          MODE="h"
          ;;
        -h|--help) usage ; exit 0 ;;
    esac
    shift
done
if [ -z "$MODE" ]; then
  MODE="s"
fi

if [ -x "$(command -v $SCREENLOCK_CMD)" ]; then
  start_idlehook
  prev_layout="$(store_kb_layout)"
  $SCREENLOCK_CMD
  restore_kb_layout "$prev_layout"
  stop_idlehook
fi
