#!/bin/sh

set -eu

is-muted() {
  wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>&1 | grep -q "MUTED"
}

unmute() {
  wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
}

signal-dwmblocks() {
  signal=$1
  kill -RTMIN+"$signal" $(pidof dwmblocks)
}

MAX_VOL=1.3
VOL_STEP=0.02
DWMBLOCKS_VOLUME_SIGNAL=4

[ -x "$(command -v wpctl)" ] || exit 1
[ "$#" -ne 1 ] && exit 2

cmd=$1
case "$cmd" in
  up)
    if is-muted; then unmute; fi
    wpctl set-volume -l "$MAX_VOL" @DEFAULT_AUDIO_SINK@ "$VOL_STEP"+
    ;;
  down)
    if is-muted; then unmute; fi
    wpctl set-volume @DEFAULT_AUDIO_SINK@ "$VOL_STEP"-
    ;;
  mute) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;
  *) exit 2 ;;
esac

signal-dwmblocks $DWMBLOCKS_VOLUME_SIGNAL

