#!/bin/sh

X11_CONFIG_DIR="$XDG_CONFIG_HOME"/X11
if [ -d "$X11_CONFIG_DIR"/xinitrc.d/ ]; then
    for f in "$X11_CONFIG_DIR"/xinitrc.d/*.sh; do
        echo $f
        [ -x "$f" ] && echo $f && $f & disown
    done
    unset f
fi

exec dwm
