#!/bin/sh

export TERMINAL=st
export BROWSER=brave

setxkbmap -layout "us,ru" -option "grp:ctrl_space_toggle"

export WALLPAPER_FILE=~/Pictures/walls/ny_432_Park_Ave.jpg

# Java gui application fix for tiling wm
# https://wiki.archlinux.org/title/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
