#!/bin/sh

export TERMINAL=st
export BROWSER=brave

# Java gui application fix for tiling wm
# https://wiki.archlinux.org/title/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
